/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package parkinglot;

/**
 *
 * @author Shazka Systems
 */
public class WelcomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form WelcomeScreen
     */
    public WelcomeScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBafresh = new javax.swing.JButton();
        jBcontinue = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jBafresh.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jBafresh.setForeground(new java.awt.Color(0, 0, 0));
        jBafresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parkinglot/refresh.png"))); // NOI18N
        jBafresh.setText("Start afresh");
        jBafresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBafreshActionPerformed(evt);
            }
        });

        jBcontinue.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jBcontinue.setForeground(new java.awt.Color(0, 0, 0));
        jBcontinue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parkinglot/delete archive.png"))); // NOI18N
        jBcontinue.setText("Continue With Data");
        jBcontinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcontinueActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parkinglot/CarBackground.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jBcontinue, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBafresh, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBcontinue, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBafresh, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBcontinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcontinueActionPerformed
        Mainframe obj=new Mainframe();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBcontinueActionPerformed

    private void jBafreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBafreshActionPerformed
        //call the function to start the files afresh
        startAfresh();
        Mainframe obj=new Mainframe();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBafreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBafresh;
    private javax.swing.JButton jBcontinue;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables


//Method to Start Afresh
 public void startAfresh(){
     String ParkingFile="files/Parking_Slot.txt";
     String Vehiclefile="files/Vehicle_Details.txt";
     String StaffFile="files/Staff_Details.txt";
     String studentFile="files/Student_Details.txt";
     String visitorFile="files/Visitor_Details.txt";
     
     String heaader="ID\tType\tSlotNumber\tPlatenumber";
     String student="ID\tName\tPhone";
     String staff="ID\tName\tPhone\tDesgnation";
     String visitor="ID\tName\tPhone";
     String vehicle="V_Name\tColor\tType\tplateNo";
     File_Writer obj=new File_Writer();
     obj.clearFile(visitorFile);
     obj.clearFile(Vehiclefile);
     obj.clearFile(StaffFile);
     obj.clearFile(studentFile);
     obj.clearFile(ParkingFile);
     
     //Write the header of each file
     obj.Witer_into_File(ParkingFile, heaader);
     obj.Witer_into_File(Vehiclefile, vehicle);
     obj.Witer_into_File(StaffFile, staff);
     obj.Witer_into_File(studentFile, student);
     obj.Witer_into_File(visitorFile, visitor);
 
 
 }

}
